server:
  port: 8080
  servlet:
    context-path: /aihulk

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.30.148:3306/aihulk?autoReconnect=true&characterEncoding=UTF8
    username: aihulk
    password: aihulk3.1415Ss
  mail:
    host: smtp.gmail.com
    port: 465
    username: aihulk2019@gmail.com
    password: aihulk3.1415
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  redis:
    host: '47.93.30.148'
    port: 6379
    password: 'aihulk3.1415'
    database: 0
    jedis:
      pool:
        max-active: 16
        max-idle: 4
        min-idle: 2

#mybatis config
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

sys-config:
  enable_email_url: 'localhost:8080/user/enableEmail'

ali_msg:
  url: dysmsapi.aliyuncs.com
  access_key: LTAInEIPW2SxgazE
  secret: xYoAyW394TgD43tvAfrm2Q8bsPZZ0R

