spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.143.248.92:3306/rule_test?autoReconnect=true&characterEncoding=UTF8
    username: root
    password: rulengine

#mybatis config
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
