server:
  port: 8080
  servlet:
    context-path: /aihulk

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3306/aihulk?autoReconnect=true&characterEncoding=UTF8
    username: xxx
    password: xxx
  mail:
    host: smtp.gmail.com
    port: 465
    username: xxx
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  redis:
    host: xxx
    port: 6379
    password: 'xxx'
    database: 0
    jedis:
      pool:
        max-active: 16
        max-idle: 4
        min-idle: 2

#mybatis config
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

sys_config:
  enable_email_url: 'localhost:8080/user/enableEmail'
  login_filter_enable: false

ali_msg:
  url: xxx
  access_key: xxx
  secret: xxx

