spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.30.148:3306/aihulk?autoReconnect=true&characterEncoding=UTF8
    username: aihulk
    password: aihulk3.1415Ss

#mybatis config
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
